In [29]:
#importing packages.
import pandas as pd
from collections import Counter

In [18]:
#DATA COLLECTION - fetching raw database in csv format from url.
url = 'https://raw.githubusercontent.com/coinmetrics-io/data/master/csv/btc.csv'
raw_data = pd.read_csv(url)
raw_data.tail()

,time,AdrActCnt,BlkCnt,BlkSizeByte,BlkSizeMeanByte,CapMVRVCur,CapMrktCurUSD,CapRealUSD,DiffMean,FeeMeanNtv,...,TxTfrValAdjUSD,TxTfrValMeanNtv,TxTfrValMeanUSD,TxTfrValMedNtv,TxTfrValMedUSD,TxTfrValNtv,TxTfrValUSD,VtyDayRet180d,VtyDayRet30d,VtyDayRet60d
4321,2020-11-02,777173.0,95.0,126097116.0,1.327338e+06,2.065861,2.519536e+11,1.219606e+11,1.999734e+13,0.000957,...,4.481868e+09,1.006091,13678.369907,0.010032,136.386491,652816.978898,8.875416e+09,0.026388,0.018827,0.019009
4322,2020-11-03,1029970.0,140.0,179259297.0,1.280424e+06,2.094975,2.594037e+11,1.238219e+11,1.775065e+13,0.000858,...,7.255377e+09,1.102767,15435.334133,0.009444,132.188269,967319.500969,1.353949e+10,0.025889,0.019200,0.019164
4323,2020-11-04,1175181.0,159.0,214138744.0,1.346785e+06,2.108234,2.618684e+11,1.242122e+11,1.678778e+13,0.000643,...,4.860452e+09,0.716848,10128.455375,0.008630,121.934549,610103.823879,8.620247e+09,0.025869,0.019199,0.018504
4324,2020-11-05,1071518.0,147.0,188078794.0,1.279448e+06,2.307493,2.892633e+11,1.253583e+11,1.678778e+13,0.000831,...,6.896637e+09,0.947055,14780.185040,0.010560,164.807879,835637.914064,1.304136e+10,0.026765,0.024748,0.022112
4325,2020-11-06,1080743.0,153.0,194685185.0,1.272452e+06,2.299192,2.895100e+11,1.259182e+11,1.678778e+13,0.000684,...,5.377085e+09,0.798253,12467.889939,0.008849,138.219785,706950.322346,1.104184e+10,0.025758,0.024822,0.022120

In [16]:
#Info from raw_data
#43 columns and 4326 rows
#All columns are floats, except the first column 'time' (object type), which is the date.
#Column PriceUSD, the price of bitcoin in USD, has 3765 entries.
#For modeling purposes we may have to drop the rows where PriceUSD is null.
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4326 entries, 0 to 4325
Data columns (total 43 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   time                4326 non-null   object
 1   AdrActCnt           4326 non-null   float64
 2   BlkCnt              4326 non-null   float64
 3   BlkSizeByte         4326 non-null   float64
 4   BlkSizeMeanByte     4320 non-null   float64
 5   CapMVRVCur          3765 non-null   float64
 6   CapMrktCurUSD       3765 non-null   float64
 7   CapRealUSD          4326 non-null   float64
 8   DiffMean            4320 non-null   float64
 9   FeeMeanNtv          4068 non-null   float64
 10  FeeMeanUSD          3765 non-null   float64
 11  FeeMedNtv           4068 non-null   float64
 12  FeeMedUSD           3765 non-null   float64
 13  FeeTotNtv           4326 non-null   float64
 14  FeeTotUSD           3765 non-null   float64
 15  HashRate            4320 non-null   float64
 16  IssContNtv          4320 non-null   float64
 17  IssContPctAnn       4320 non-null   float64
 18  IssContUSD          3765 non-null   float64
 19  IssTotNtv           4320 non-null   float64
 20  IssTotUSD           3765 non-null   float64
 21  NVTAdj              4066 non-null   float64
 22  NVTAdj90            3676 non-null   float64
 23  PriceBTC            4326 non-null   float64
 24  PriceUSD            3765 non-null   float64
 25  ROI1yr              3400 non-null   float64
 26  ROI30d              3735 non-null   float64
 27  SplyCur             4326 non-null   float64
 28  SplyExpFut10yrCMBI  4320 non-null   float64
 29  SplyFF              4326 non-null   float64
 30  TxCnt               4326 non-null   float64
 31  TxTfrCnt            4326 non-null   float64
 32  TxTfrValAdjNtv      4326 non-null   float64
 33  TxTfrValAdjUSD      3765 non-null   float64
 34  TxTfrValMeanNtv     4068 non-null   float64
 35  TxTfrValMeanUSD     3765 non-null   float64
 36  TxTfrValMedNtv      4068 non-null   float64
 37  TxTfrValMedUSD      3765 non-null   float64
 38  TxTfrValNtv         4326 non-null   float64
 39  TxTfrValUSD         3765 non-null   float64
 40  VtyDayRet180d       3585 non-null   float64
 41  VtyDayRet30d        3735 non-null   float64
 42  VtyDayRet60d        3705 non-null   float64
dtypes: float64(42), object(1)
memory usage: 1.4+ MB

In [35]:
#The variable definition for each column is in the 'metrics_info.csv' file.
metrics_info = pd.read_csv('metrics_info.csv').transpose()
metrics_info

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
id,AdrActCnt,BlkCnt,BlkSizeByte,BlkSizeMeanByte,CapMVRVCur,CapMrktCurUSD,CapRealUSD,DiffMean,FeeMeanNtv,FeeMeanUSD,...,TxTfrValAdjUSD,TxTfrValMeanNtv,TxTfrValMeanUSD,TxTfrValMedNtv,TxTfrValMedUSD,TxTfrValNtv,TxTfrValUSD,VtyDayRet180d,VtyDayRet30d,VtyDayRet60d
name,"Addresses, active, count","Block, count","Block, size, bytes","Block, size, mean, bytes","Capitalization, MVRV, current supply","Capitalization, market, current supply, USD","Capitalization, realized, USD","Difficulty, mean","Fees, transaction, mean, native units","Fees, transaction, mean, USD",...,"Transactions, transfers, value, adjusted, USD","Transactions, transfers, value, mean, native u...","Transactions, transfers, value, mean, USD","Transactions, transfers, value, median, native...","Transactions, transfers, value, median, USD","Transactions, transfers, value, native units","Transactions, transfers, value, USD","Volatility, daily returns, 180d","Volatility, daily returns, 30d","Volatility, daily returns, 60d"
category,Addresses,Network Usage,Network Usage,Network Usage,Market,Market,Market,Mining,Fees and Revenue,Fees and Revenue,...,Transactions,Transactions,Transactions,Transactions,Transactions,Transactions,Transactions,Market,Market,Market
subcategory,Active,Blocks,Blocks,Blocks,Market Capitalization,Market Capitalization,Market Capitalization,Difficulty,Fees,Fees,...,Transfer Value,Transfer Value,Transfer Value,Transfer Value,Transfer Value,Transfer Value,Transfer Value,Volatility,Volatility,Volatility
type,Sum,Sum,Sum,Mean,Ratio,Product,Product,Mean,Mean,Mean,...,Sum,Mean,Mean,Median,Median,Sum,Sum,Ratio,Ratio,Ratio
unit,Addresses,Blocks,Bytes,Bytes,Dimensionless,USD,USD,Dimensionless,Native units,USD,...,USD,Native units,USD,Native units,USD,Native units,USD,Dimensionless,Dimensionless,Dimensionless
interval,1 day,1 day,1 day,1 day,1 day,1 day,1 day,1 day,1 day,1 day,...,1 day,1 day,1 day,1 day,1 day,1 day,1 day,180 days,30 days,60 days
interval_rt,1 block,NaN,1 block,NaN,NaN,NaN,NaN,1 block,1 block,1 block,...,NaN,1 block,1 block,1 block,1 block,1 block,1 block,NaN,NaN,NaN
description,The sum count of unique addresses that were ac...,The sum count of blocks created that interval ...,The sum of the size (in bytes) of all blocks c...,The mean size (in bytes) of all blocks created...,The ratio of the sum USD value of the current ...,The sum USD value of the current supply. Also ...,The sum USD value based on the USD closing pri...,The mean difficulty of finding a hash that mee...,The mean fee per transaction in native units t...,The USD value of the mean fee per transaction ...,...,The USD value of the sum of native units trans...,The mean count of native units transferred per...,The sum USD value of native units transferred ...,The median count of native units transferred p...,The median USD value transferred per transfer ...,"The sum of native units transferred (i.e., the...",The sum USD value of all native units transfer...,"The 180D volatility, measured as the standard ...","The 30D volatility, measured as the standard d...","The 60D volatility, measured as the standard d..."

In [32]:
#null values of PriceUSD column
Counter(pd.isnull(raw_data['PriceUSD']))

Counter({True: 561, False: 3765})

In [13]:
#Sumamry statistics
raw_data.describe()

,AdrActCnt,BlkCnt,BlkSizeByte,BlkSizeMeanByte,CapMVRVCur,CapMrktCurUSD,CapRealUSD,DiffMean,FeeMeanNtv,FeeMeanUSD,...,TxTfrValAdjUSD,TxTfrValMeanNtv,TxTfrValMeanUSD,TxTfrValMedNtv,TxTfrValMedUSD,TxTfrValNtv,TxTfrValUSD,VtyDayRet180d,VtyDayRet30d,VtyDayRet60d
count,4.326000e+03,4326.000000,4.326000e+03,4.320000e+03,3765.000000,3.765000e+03,4.326000e+03,4.320000e+03,4068.000000,3765.000000,...,3.765000e+03,4068.000000,3765.000000,4.068000e+03,3.765000e+03,4.326000e+03,3.765000e+03,3585.000000,3735.000000,3705.000000
mean,3.377091e+05,151.584836,7.136849e+07,4.785103e+05,2.031592,4.826360e+10,2.585722e+10,2.447282e+12,0.000926,1.108735,...,7.918861e+08,96.108062,3982.016817,5.538197e+01,3.727550e+01,1.052981e+06,2.473295e+09,0.048975,0.043963,0.046011
std,3.306305e+05,35.415637,6.578252e+07,4.458509e+05,3.025173,6.969464e+10,3.985543e+10,4.826519e+12,0.007786,3.731013,...,1.235124e+09,681.506111,5439.699494,6.440987e+02,5.172915e+01,1.925715e+06,4.355644e+09,0.021259,0.029778,0.026854
min,0.000000e+00,0.000000,0.000000e+00,2.150000e+02,0.386829,1.776705e+05,0.000000e+00,1.000000e+00,0.000000,0.000000,...,4.647065e+02,0.010000,0.762873,1.000000e-08,8.203471e-08,0.000000e+00,5.874592e+02,0.020298,0.007481,0.010406
25%,1.651325e+04,138.000000,3.232264e+06,2.175206e+04,1.239558,2.690790e+08,4.296370e+07,1.508590e+06,0.000138,0.031492,...,1.174205e+07,1.537546,519.201411,1.188221e-02,3.363051e+00,3.572101e+05,4.750890e+07,0.032676,0.024652,0.027718
50%,2.213640e+05,152.000000,4.875393e+07,3.298404e+05,1.666092,6.776417e+09,4.161289e+09,4.000747e+10,0.000231,0.109857,...,1.452220e+08,3.534813,1691.184235,2.880000e-02,1.463417e+01,6.791128e+05,5.422188e+08,0.042614,0.035440,0.038476
75%,6.366198e+05,166.000000,1.344751e+08,9.233349e+05,2.211287,9.617654e+10,4.376520e+10,1.427972e+12,0.000684,0.735498,...,1.376642e+09,21.957797,6173.666058,1.000018e-01,6.555249e+01,1.285331e+06,3.808503e+09,0.059117,0.053311,0.057797
max,1.290363e+06,692.000000,2.565337e+08,1.427240e+06,146.038332,3.288988e+11,1.259182e+11,1.999734e+13,0.220000,56.308124,...,1.082210e+10,22175.000000,51124.770624,2.217500e+04,5.348536e+02,6.725965e+07,4.877049e+10,0.109532,0.191722,0.143269

In [23]:
#setting date column as index and droping it from columns
raw_data.index = raw_data['time']
raw_data = raw_data.drop('time', axis='columns')
raw_data.tail()

,AdrActCnt,BlkCnt,BlkSizeByte,BlkSizeMeanByte,CapMVRVCur,CapMrktCurUSD,CapRealUSD,DiffMean,FeeMeanNtv,FeeMeanUSD,...,TxTfrValAdjUSD,TxTfrValMeanNtv,TxTfrValMeanUSD,TxTfrValMedNtv,TxTfrValMedUSD,TxTfrValNtv,TxTfrValUSD,VtyDayRet180d,VtyDayRet30d,VtyDayRet60d
time,,,,,,,,,,,,,,,,,,,,,
2020-11-02,777173.0,95.0,126097116.0,1.327338e+06,2.065861,2.519536e+11,1.219606e+11,1.999734e+13,0.000957,13.007339,...,4.481868e+09,1.006091,13678.369907,0.010032,136.386491,652816.978898,8.875416e+09,0.026388,0.018827,0.019009
2020-11-03,1029970.0,140.0,179259297.0,1.280424e+06,2.094975,2.594037e+11,1.238219e+11,1.775065e+13,0.000858,12.013911,...,7.255377e+09,1.102767,15435.334133,0.009444,132.188269,967319.500969,1.353949e+10,0.025889,0.019200,0.019164
2020-11-04,1175181.0,159.0,214138744.0,1.346785e+06,2.108234,2.618684e+11,1.242122e+11,1.678778e+13,0.000643,9.090230,...,4.860452e+09,0.716848,10128.455375,0.008630,121.934549,610103.823879,8.620247e+09,0.025869,0.019199,0.018504
2020-11-05,1071518.0,147.0,188078794.0,1.279448e+06,2.307493,2.892633e+11,1.253583e+11,1.678778e+13,0.000831,12.973713,...,6.896637e+09,0.947055,14780.185040,0.010560,164.807879,835637.914064,1.304136e+10,0.026765,0.024748,0.022112
2020-11-06,1080743.0,153.0,194685185.0,1.272452e+06,2.299192,2.895100e+11,1.259182e+11,1.678778e+13,0.000684,10.684208,...,5.377085e+09,0.798253,12467.889939,0.008849,138.219785,706950.322346,1.104184e+10,0.025758,0.024822,0.022120